--liquibase formatted sql
--changeset bkvdm:1
CREATE TABLE IF NOT EXISTS notification_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    date_time TIMESTAMP NOT NULL,
    notification VARCHAR(255) NOT NULL
);